### PR TITLE
(Cgt 2915) - Injectable form validation and updates to CorrespondenceDetails to store country code instead of entered string in model

### PR DESCRIPTION
**Pull request by euptonqa**

### CODE REVIEW

**Comment by euptonqa** [comment]
Will resolve merge conflicts once all logic-linking branches are merged in/first story is ready for deployment.

**Comment by DavidWoodward42** [comment]
Logic linking has been merged in now :)

**Comment by DavidWoodward42** [comment]
Sorry Emma, this does the validation but it only allows the user to enter a country code not an actual country and then convert it to the code for the model.  It also needs an additional enforcement that when GB is supplied then the postcode is becomes mandatory. (This is validation done after the apply/unapply to the model at the end of the form).

**Comment by euptonqa** [comment]
No longer needed

**Pull request closed without merging**
